CREATE SCHEMA EXERCICIOFIX01;
USE EXERCICIOFIX01;

#CRIANDO TABELA PARTICIPANTES ---------------------------------------------
CREATE TABLE IF NOT EXISTS PARTICIPANTES(
NUM_INSCRICAO INT, #CRIANDO CHAVE PRIMÁRIA COMPOSTA
CPF VARCHAR(14), #CRIANDO CHAVE PRIMÁRIA COMPOSTA
PRIMARY KEY(NUM_INSCRICAO, CPF), #CRIANDO CHAVE PRIMÁRIA COMPOSTA

NOME VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL,
EMPRESA VARCHAR(100)
);

#alter table add participantes add email varchar(20);
# ou alter table add column participantes add email varchar(20);
#alter table participantes drop column email; removendo coluna

#CRIANDO TABELA LOCAIS ---------------------------------------------
CREATE TABLE IF NOT EXISTS LOCAIS(
#NOME_DO_ATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE(OPCIONAL)
ID_LOCAL INT PRIMARY KEY,
NOME_LOCAL VARCHAR(100) NOT NULL,
LOG_LOCAL VARCHAR(100) NOT NULL,
NUMLOG_LOCAL INT,
BAIRRO_LOCAL VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NOT NULL,
CEP VARCHAR(20) NOT NULL,
CAPACIDADE INT NOT NULL
);

#CRIANDO A TABELA EVENTOS
CREATE TABLE IF NOT EXISTS EVENTOS(
#NOME_DO_ATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE(OPCIONAL)
ID_EVENTO INT PRIMARY KEY,
NOME_EVENTO VARCHAR(100) NOT NULL,
DATA_EVENTO DATE NOT NULL,
ENTIDADE_EVENTO VARCHAR(100) NOT NULL,
LOCAL_EVENTO INT,
# CONSTRAINT FK_FORNECEDOR FOREIGN KEY (LOCAL_EVENTO) (NÃO É OBRIGATORIO CONSTRAINT, TA FAZENDO PRIMEIRO SEM)
FOREIGN KEY (LOCAL_EVENTO) REFERENCES LOCAIS(ID_LOCAL));


#CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA


#CRIANDO A TABELA ATIVIDADES ---------------------------------------------
CREATE TABLE IF NOT EXISTS ATIVIDADES(
ID_ATIVIDADE INT PRIMARY KEY,
NOME_ATV VARCHAR(100) NOT NULL,
DATA_ATV DATE NOT NULL,
HORA_ATV TIME NOT NULL,

EVENTO_ATV INT NOT NULL,
FOREIGN KEY (EVENTO_ATV) REFERENCES EVENTOS(ID_EVENTO)
);

#CRIANDO TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS) ---------------------------------------------

#CRIANDO A TABELA PARTICIPANTE_EVENTO ---------------------------------------------
#CRIANDO TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)
CREATE TABLE IF NOT EXISTS PARTICIPANTE_EVENTO(
PE_INSCRICAO INT,
PE_CPF VARCHAR(14),
PE_EVENTO INT,
PRIMARY KEY(PE_INSCRICAO,PE_CPF,PE_EVENTO),
FOREIGN KEY(PE_INSCRICAO,PE_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
FOREIGN KEY(PE_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
CONSTRAINT PARTICIP_ATIVID_PK_PEAV1 FOREIGN KEY(PE_INSCRICAO,PE_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
CONSTRAINT PARTICIP_ATIVID_PK_PEAV3 FOREIGN KEY(PE_EVENTO) REFERENCES ATIVIDADES(ID_ATIVIDADE)
);

CREATE TABLE IF NOT EXISTS PARTICIPANTE_ATIVIDADE(
PA_INSCRICAO INT,
PA_CPF VARCHAR(14),
PA_EVENTO INT,
PRIMARY KEY(PA_INSCRICAO,PA_CPF),
FOREIGN KEY(PA_INSCRICAO,PA_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
FOREIGN KEY(PA_EVENTO) REFERENCES ATIVIDADES(ID_ATIVIDADE),
CONSTRAINT PARTICIP_ATIVID_PK_PAATV1 FOREIGN KEY(PA_INSCRICAO,PA_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
CONSTRAINT PARTICIP_ATIVID_PK_PAATV3 FOREIGN KEY(PA_EVENTO) REFERENCES ATIVIDADES(ID_ATIVIDADE)
);

#CONSTRAINT PARTICIP_ATIVID_PK_PARTICIPANTES FOREIGN KEY(INSCRICAO) REFERENCES PARTICIPANTES(NUM_INSCRICAO),
#CONSTRAINT PARTICIP_ATIVID_PK_PARTICIPANTES FOREIGN KEY(CPF) REFERENCES PARTICIPANTES(CPF),
#CONSTRAINT PARTICIP_ATIVID_PK_PARTICIPANTES FOREIGN KEY(ATIVIDADE) REFERENCES ATIVIDADES(ID_ATIVIDADE)

#INSERIR CONSTRAINT
#DROP SCHEMA EXERC_FIX