#CREATE SCHEMA EXERCICIOFIX03;
USE EXERCICIOFIX03;

CREATE TABLE IF NOT EXISTS ESPECTADORES(
ID_ESPECT INT PRIMARY KEY,
TEL_ESPECT VARCHAR(20),
EMAIL_ESPEC VARCHAR(50) NOT NULL,
NOME_ESPECT VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS SALAS(
ID_SALA INT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CAPACIDADE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMES( 
ID_FILME INT PRIMARY KEY,
NOME_FILME VARCHAR(100) NOT NULL,
DISTRIBUIDOR_FILME VARCHAR(100) NOT NULL,
TEMPO_FILME INT NOT NULL,
DIRETOR VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SESSOES( 
ID_SESSAO INT PRIMARY KEY,
FILME_SESSAO INT,
SALA_SESSAO INT,
CONSTRAINT FK_FIL_SES FOREIGN KEY (FILME_SESSAO) REFERENCES FILMES(ID_FILME),
CONSTRAINT FK_SAL_SES FOREIGN KEY (SALA_SESSAO) REFERENCES SALAS(ID_SALA)
);

CREATE TABLE IF NOT EXISTS INGRESSOS(
ID_INGRESSO INT PRIMARY KEY,
DATA_ING DATE NOT NULL,
HORA_ING TIME NOT NULL,
SESSAO_ING INT,
ESPECTADOR_ING INT,
CONSTRAINT FK_SE_ING FOREIGN KEY (SESSAO_ING) REFERENCES SESSOES(ID_SESSAO),
CONSTRAINT FK_ES_ING FOREIGN KEY (ESPECTADOR_ING) REFERENCES ESPECTADORES(ID_ESPECT)
);